// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4u8SZn3tAR2ibN3V_dLjih_ooRhqSyQ',
    appId: '1:496252375384:web:5de2a3f59bd57c3062552d',
    messagingSenderId: '496252375384',
    projectId: 'gps4-4354d',
    authDomain: 'gps4-4354d.firebaseapp.com',
    databaseURL:
        'https://gps4-4354d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps4-4354d.appspot.com',
    measurementId: 'G-JVM7F1WHJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6YrKrsityn9RLxw1SRh_sKjVGgaKuUM',
    appId: '1:496252375384:android:a1083babb51ae2bc62552d',
    messagingSenderId: '496252375384',
    projectId: 'gps4-4354d',
    databaseURL:
        'https://gps4-4354d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps4-4354d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWtT7iksc4KOFRjj_oUxeq6FhyLi-kFA',
    appId: '1:496252375384:ios:fdeec63b2155573c62552d',
    messagingSenderId: '496252375384',
    projectId: 'gps4-4354d',
    databaseURL:
        'https://gps4-4354d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps4-4354d.appspot.com',
    iosClientId:
        '496252375384-hmokqkdm4t87ohqoedqp74bsu25n25mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWtT7iksc4KOFRjj_oUxeq6FhyLi-kFA',
    appId: '1:496252375384:ios:1607dcaecf2ae4ee62552d',
    messagingSenderId: '496252375384',
    projectId: 'gps4-4354d',
    databaseURL:
        'https://gps4-4354d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps4-4354d.appspot.com',
    iosClientId:
        '496252375384-scf80228095avqbg52c8pestce9u5p0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fb.RunnerTests',
  );
}
